FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY server.mjs ./server.mjs

EXPOSE 5173
CMD ["node", "server.mjs"]