-- CreateEnum
CREATE TYPE "ReactionType" AS ENUM ('GOOD', 'FUTURE', 'COMPLEX');

-- AlterTable
ALTER TABLE "Idea" ADD COLUMN     "complexCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fireScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "futureCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "goodCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "IdeaLike" ADD COLUMN     "reactionType" "ReactionType" NOT NULL DEFAULT 'GOOD';
